### ISSUE TITLE
Nimdow does not attach existing windows

### ISSUE THREAD

**Issue by 0xACE** [avahe-kellenberger/nimdow#105]
I have a simple script:

```sh
while true; do
dwm
nimdow
done
```
to toggle between my window managers.

When `nimdow` starts, `nimdow` doesn't attach the existing windows, and from my limited testing i can't control the windows that exist before `nimdow` spawns.

I expected `nimdow` to attach or be able to adopt the existing applications.

**Comment by avahe-kellenberger** [comment]
Yep, this is what #8 is about. I can add it sooner than later if this is important for you to have
