### ISSUE TITLE
winking bar

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#106]
**Describe the bug**
The bar winks

**Steps to reproduce**
1. Run [this script](https://gist.github.com/unihernandez22/1a4c48ccfa9f4bdab9b94fa599359994)
2. See the error

**Comment by avahe-kellenberger** [comment]
Interesting, I'm not seeing any flickering (if that's what you mean by winking).

What's your nimdow version? `nimdow -v` will show it.

**Comment by unihernandez22** [comment]
> What's your nimdow version? `nimdow -v` will show it.

v0.7.3

**Comment by avahe-kellenberger** [comment]
I'm still unable to recreate this - if you can think of any other pertinent information, please let me know.

**Comment by unihernandez22** [comment]
I changed my OS, so now I don't have the issue. I'll close this, because I don't know what was causing it.
