### ISSUE TITLE
Document the process of building nimdow 

### ISSUE THREAD

**Issue by xmonader** [avahe-kellenberger/nimdow#108]
Hi! thank you for the great project! 

It'd be really amazing if you can provide some tutorials based on this codebase on how to develop your own window manager and maybe convert it to a book?

**Comment by avahe-kellenberger** [comment]
Hi there!

Unfortunately, there is a LOT to cover. Here are some resources I've used:

1. [A basic overview and small window manager example](https://jichu4n.com/posts/how-x-window-managers-work-and-how-to-write-one-part-i/)
2. [Xlib Documentation](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html)
3. [dwm source code](https://git.suckless.org/dwm/) (you can also research the source code of other window managers, like openbox, i3, awesomeWM, etc)
4. [This dude's manual](https://tronche.com/gui/x/xlib/) which I use a lot

It has been a lot of reading with trial and error to figure out what's going on. Don't let the walls of text stop you, pretty much every word is there for a reason.

I'd also check out [Qtile](http://www.qtile.org/) if you want something easier to read than c/c++, it's written in Python.

If you have questions or just want to share, I'm on the freenode and rizon IRC networks as `Prestige`.
