### ISSUE TITLE
[branch urgent-windows] floating applications have left-padding

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#114]
**Describe the bug**
When I launch a floating program, it somehow has left-padding.

**To Reproduce**
1. launch `pavucontrol-qt`

**Expected behavior**
it should have opened the floating window somewhere accessible on screen (centre would be the best pos imo)

**Screenshots**
![image](https://user-images.githubusercontent.com/32128756/96333893-b7784100-107d-11eb-8779-46546f4324c2.png)

**Additional context**

**Comment by avahe-kellenberger** [comment]
Notes: Able to reproduce with any floating window, but only on my second monitor.

It seems like the width of the first monitor may be getting added to its x position.

**Comment by avahe-kellenberger** [comment]
Will release this fix when I merge in the urgent-windows branch.
