### ISSUE TITLE
Title position on the bar

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#115]
I'd like to be able to define in my config file where I want titles to be drawn on the bar. The options should be: left, centre, right. However, it maybe easy to let users also define padding. So, if I have padding 5px in config as well as position left, it will anchor the text to left with 5px padding.

**Comment by dakyskye** [comment]
Can't wait for this feature to get implemented haha. Don't have much space on the bar after switching to single monitor setup, as now I've merged my two bars into one.

**Comment by avahe-kellenberger** [comment]
I could do this after the current PR has been merged
