### ISSUE TITLE
Can't start it using .xinitrc

### ISSUE THREAD

**Issue by Productive2** [avahe-kellenberger/nimdow#119]
Nimdow doesn't start with the following .xinitrc's:

```
DISPLAY=:0
exec nimdow
```

```
exec nimdow
```

(Display is indeed display 0, checked in .tmp/X11-unix)

These are tested with lightdm session "default", which should execute the xinitrc.

Also, it's not possible to start it with this lightdm session either (in /usr/share/xsessions/)

```
[blah blah]
Name=blah blah
Exec=/usr/local/bin/startnimdow.sh
```

where startnimdow.sh is a chmod+x'd file:

```
DISPLAY=:0 /home/$(whoami)/.nimble/bin/nimdow
```

All of the above configurations crash nimdow, and return to the lightdm screen immediately.

Also, I tried putting "nimdow" or "DISPLAY=:0 nimdow" in the xfce config, as a replacement of bspwm (which replaced xfce4-wm long time ago), and it didn't start nimdow (checked with ps -e)

The only way I could actually start nimdow is by launching xfce-session without a wm, and then from a tty I did
DISPLAY=:0 nimdow from the same user.

**Comment by avahe-kellenberger** [comment]
Is there a reason you're specifying the display?

**Comment by dakyskye** [comment]
`nimdow` or `exec nimdow` line works :ok_hand: for me, but I don't specify `DISPLAY`.

**Comment by Productive2** [comment]
> Is there a reason you're specifying the display?

Out of habit, because it's the only way I could start it from another tty.

> `nimdow` or `exec nimdow` line works ok_hand for me, but I don't specify `DISPLAY`.

I tried as well, just tried it again to confirm. Does not work :(

Now, I'd love to help debugging. Where can I find the logs?

**Comment by avahe-kellenberger** [comment]
Sounds like the program isn't even able to start running. Can you look for your xorg log files? Typically in /var/log/ as Xorg.0.log, or in ~/.local/share/xorg/

Maybe there's a missing lib on your system that's needed like xft

**Comment by avahe-kellenberger** [comment]
Closing till further info is provided.
