### ISSUE TITLE
Status bar background color rendering

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#120]
**Describe the bug**

1. The height should match the height of the font
2. The x location seems to be off by 1 pixel (need to verify)

**To Reproduce**

1. Run the following script (provided by @dakyskye - thank you)

```bash
#!/usr/bin/bash

ARROW_A=$'\x1b[0m\x1b[38;2;167;122;196m\x1b[0m\x1b[48;2;167;122;196m'
ARROW_B=$'\x1b[38;2;113;151;231m\x1b[0m\x1b[48;2;113;151;231m'
ARROW_C=$'\x1b[38;2;167;122;196m\x1b[0m\x1b[48;2;167;122;196m'

status="${ARROW_A} ${ARROW_B} btw ${ARROW_C} <3 ${ARROW_B} distrotube ${ARROW_C} XDD ${ARROW_B} :^P"
xsetroot -name "$status"
echo "$status"
```

2. Observe the correct rendering in the terminal, compared to the status bar.

**Notes**

The bug was observed with a barHeight of 20 and the following fonts:

```toml
barFonts = [
    "JetBrains Mono:size=8:antialias=true",
    "FontAwesome:size=9:antialias=true",
    "DejaVu Serif:size=8:antialias=true",
  ]
```

**Comment by dakyskye** [comment]
This is what I meant. Would be cool if there was an option to use Different font for certain part of the bar, so I could use bigger font for arrow icons and smaller for text.
![image](https://user-images.githubusercontent.com/32128756/118330133-63044980-b518-11eb-880f-16a259fb0c1e.png)

**Comment by avahe-kellenberger** [comment]
Technically this can be done by setting barFonts - if the arrow chars use a unique font, the size given would take over.
I'd like to test this out when we can talk live, next.

I would need to know the fonts and particular (arrow) characters

**Comment by dakyskye** [comment]
@avahe-kellenberger yeah, those arrows are found in many different fonts and I want them to use specific font size, because if I increase my font size the text size as well as arrows size will increase which I don't want.

I was thinking about what lemonbar does:
```toml
	barFonts = [
		"JetBrains Mono:size=8:antialias=true",
		"Font Awesome 5 Free Solid:size=9:antialias=true",
		"Font Awesome 5 Brands Regular:size=9:antialias=true",
		"DejaVu Serif:size=8:antialias=true",
		"JetBrains Mono:size=13:antialias=true",
	]
```

```bash
xsetroot -name "Hello %{F5} there %{F}
```
^^ there text without font specified (so `Hello  there `) should use first font as expected and those arrow icons should use the 5th font (which has size of 13).

**Comment by PMunch** [comment]
Hmm, the ANSI CSI SGR system that we currently use to define colours also has the possibility to define 9 alternative fonts. We could easily extend the parser to include support for fonts so you can have 10 total fonts (1 default, and 9 alternative ones).
