### ISSUE TITLE
Support for window swallowing

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#126]
I'd love to see [window swallowing](https://dwm.suckless.org/patches/swallow/#:~:text=h%20swallow%20a%20window%20opened,screen%20with%20many%20unusable%20terminals.) in Nimdow. So what it does is that if you start a GUI program from terminal emulator and your shell has to wait for it to finish, the window should get swallowed until the program exits and then respawn in the state it was wherever it was placed before.

**Comment by avahe-kellenberger** [comment]
Since you could do this with [devour](https://github.com/salman-abedin/devour) I don't think I'd care to implement it in Nimdow. What are your thoughts?

[Vid of DT reviewing devour](https://www.youtube.com/watch?v=mBNLzHcUtTo)

**Comment by dakyskye** [comment]
I'd prefer Nimdow to have it built-in to using third party tools. Should be quite easy to add it to Nimdow (looking at devour source, I geel like that) For now, I'll stick with devour though.
