### ISSUE TITLE
Implement click to raise to fix floating window hierarchy

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#127]
**Describe the bug**
There is no hierarchy for floating windows. So, if you open a floating window of size 800x600 (centred) and then open another floating window of size (anything smaller than 899x600) 500x300 (also centred) the latter window gets focused, but as soon as you focus the former window, the latter get's hidden as the former gets on top of it.

**To Reproduce**
1. open a floating window and centre it
2. open another floating window which is smaller than the already opened one and centre it
3. focus the former window

**Expected behavior**
Floating windows should have hierarchy.
The that was opened first should not rerender on top of a window opened later.

**Screenshots**
I'll attach a GIF tomorrow.

**Comment by avahe-kellenberger** [comment]
This is the expected behavior until click to raise is implemented

**Comment by avahe-kellenberger** [comment]
Closed via #147
