### ISSUE TITLE
Allow for the number of master windows to be set per tag in the config

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#128]
Per #52:
`With some windows assigned to tags this way it may also make sense to be able to configure the default number of masters on a per-tag basis.` - @PMunch 

This could take place in the `[monitors]` array,
where we can already set display strings per tag.

This number must be from 1 to 9.

Should we have a way to set the default number for all tags? Ans: Yes.

**Comment by dakyskye** [comment]
The instance is the first value of `WM_CLASS`. For example: `WM_CLASS(STRING) = "cordless", "Alacritty"` means it's an instance of Alacritty class called `cordless`. So this can be useful when you want Nimdow to assign `cordless` to certain tag. The other way would be using WM title, but I'd prefer a terminal instance called cordless.

**Comment by avahe-kellenberger** [comment]
In-progress: https://github.com/avahe-kellenberger/nimdow/tree/numMasterWindowsConfig

**Comment by avahe-kellenberger** [comment]
https://github.com/avahe-kellenberger/nimdow/wiki/User-Configuration-File#num-master-windows

@PMunch
