### ISSUE TITLE
Floating windows bug after suspend

### ISSUE THREAD

**Issue by uninhm** [avahe-kellenberger/nimdow#151]
**Describe the bug**
After suspend and resume, floating windows can't be resized nor moved, even if you do it floating after resome.

**To Reproduce**
1. Suspend and resume (In my case with `elogind` in Void Linux)
2. Open a floating window
3. Try to move or resize

**Comment by avahe-kellenberger** [comment]
Is this only with floating windows? I'll have to test this out later this week

**Comment by uninhm** [comment]
> Is this only with floating windows?

You can't move nor resize tiled windows so...

**Comment by avahe-kellenberger** [comment]
I meant making a tiled window into floating, then resize

**Comment by uninhm** [comment]
> I meant making a tiled window into floating, then resize

That too. And I think that when you suspend without any window open, there is no bug...

**Comment by uninhm** [comment]
I'm not sure if suspend is the reason... Now I'm bugged, what can I do?

**Comment by avahe-kellenberger** [comment]
Enable logging in the config file, see if anything shows up after suspend? Maybe nimdow crashes or something

**Comment by avahe-kellenberger** [comment]
@uninhm Going to close this until/unless more info is provided

**Comment by uninhm** [comment]
`.nimble.log`
```
INFO [2021-06-23 13:42:41][nimdow]: Starting Nimdow v0.7.24
INFO [2021-06-23 13:42:41][ipc]: Created ipc socket: /run/user/1000/nimdow/ipc-socket.21553
ERROR [2021-06-23 13:52:18][windowmanager]: BadLength (poly request too large or internal Xlib length error)
ERROR [2021-06-23 13:52:18][windowmanager]: BadLength (poly request too large or internal Xlib length error)
ERROR [2021-06-23 15:43:01][windowmanager]: BadMatch (invalid parameter attributes)
```

**Comment by avahe-kellenberger** [comment]
Any other info on reproducing this? I can't seem to recreate it

**Comment by uninhm** [comment]
> Any other info on reproducing this? I can't seem to recreate it

Idk, it bugs after using nimdow for a while
