### ISSUE TITLE
Handle windows' resize requests

### ISSUE THREAD

**Issue by uninhm** [avahe-kellenberger/nimdow#153]

**Comment by avahe-kellenberger** [comment]
Steps to reproduce, or any more context here?

**Comment by uninhm** [comment]
> Steps to reproduce, or any more context here?

Open chrome and try to resize (?
(Click border (It shows the resize icon in mouse pointer) and drag)

**Comment by avahe-kellenberger** [comment]
So the windows don't actually request to be resized, this is something the window manager has to implement.
I *could* implement it, but we already have resizing with super + right click/drag

**Comment by uninhm** [comment]
> So the windows don't actually request to be resized

I remember I had troubles with another app, but I don't remember what app hahaha

**Comment by avahe-kellenberger** [comment]
If you find out again let me know! I'll close for now
