### ISSUE TITLE
Feature request: clickable tags and more

### ISSUE THREAD

**Issue by luis-07** [avahe-kellenberger/nimdow#159]
I absolutely love nimdow and I think it is a good dwm replacement for me but I am used to some patches and features of dwm which I also want to use in nimdow. The first patch I miss are clickable tags. The patch I miss the most is the scratchpads patch you probably now how scratchpads works. Another patch I miss is a patch which allows you to set a keybinding to a single letter if no windows are opened. Then I miss also awesome bar you probably know that too. And the last thing I miss is the ability to switch to tag 0 like in dwm.

**Comment by avahe-kellenberger** [comment]
Thanks for the feedback!

- I'd love to implement clickable tags
- Scratchpad has been implemented, see [the new scratchpad commands at the bottom of this section](https://github.com/avahe-kellenberger/nimdow/wiki/User-Configuration-File#controls-table-) or the [default configuration file](https://github.com/avahe-kellenberger/nimdow/blob/master/config.default.toml#L156)

>patch which allows you to set a keybinding to a single letter if no windows are opened
I assume you mean e.g. press `3` to navigate to tag 3 if no windows are open on the current tag? That would be nice to implement.

>I miss also awesome bar
The bar from `awesomewm`? If there are features you'd like added to nimdow's bar that awesome has, I'll need more details

>the ability to switch to tag 0 like in dwm
I believe this would show all tags at once, correct? That's possible now, but isn't a default keybinding. Would be _very_ easy to add.

---

If you could take the time to divide these up into separate issues, I'd appreciate it. I will implement these changes when I have some time.

**Comment by luis-07** [comment]
This is the clickable tags issue the others I will open soon

**Comment by luis-07** [comment]
I have to praise you because you get me away from dwm to a awesome windowmanager (nimdow) I tried many window managers but i switched back to dwm every time but this time it was different.

**Comment by avahe-kellenberger** [comment]
Thanks for the kind words - I'm glad other people are enjoying Nimdow
