### ISSUE TITLE
Invisible window with strange command

### ISSUE THREAD

**Issue by PMunch** [avahe-kellenberger/nimdow#168]
**Describe the bug**
I was playing around with commands for my clickable bar. One of the things I wanted to do was to have my notifications that I flash in the status bar area open a terminal with the whole file of notifications before clearing it. I simply tried calling my terminal alias for this into the config but calling it simply created an invisible window. Not entirely sure if it creates a window or not, but Nimdow reserves space for it. But I can't select the window in any way, so I can't close it. And running `xprop` on the area just gives me the root window.

**To Reproduce**
1. Add this to config, keyboard shortcut can obviously be whatever you want. Haven't tried a different terminal:
```toml
[[startProcess]]
command = "urxvt -e \"less /tmp/notifications\""
keys = ["b"]
modifiers = [ "super" ]
```

**Expected behavior**
I expect a terminal window to appear with that file open in less, similar to how `urxvt -e htop` works.

**Screenshots**
![Image](https://user-images.githubusercontent.com/2845482/129569356-3a2b9eed-4a05-439f-bf86-c2f829ecc237.png)

**Comment by avahe-kellenberger** [comment]
Something interesting I noticed is that you can do `urxvt -e less /tmp/notifications` without an issue - passing the command as a string causes the process to exit.

I'll keep investigating this bug, though

**Comment by PMunch** [comment]
Does urxvt get more than then first option then though?

**Comment by avahe-kellenberger** [comment]
Seems like it

**Comment by avahe-kellenberger** [comment]
I'm able to recreate this, but don't seem to be receiving any destroy or unmap notify events. This is very strange.

I might look into this later, but since it shouldn't currently be a problem I'm going to close this.
