### ISSUE TITLE
Transparent Borders on some app with Picom.

### ISSUE THREAD

**Issue by TheTrashPenguin** [avahe-kellenberger/nimdow#177]
**Describe the bug**
Hello. I am running Nimdow on Arch Linux. For some reason, some applications such as Zathura and Alacritty have a semi-transparent border if picom is running. I have opened Zathura on Leftwm with picom running and it doesn't have the semi-transparent border.
Similar Issues on other window managers are: [1173 for herbsluftwm](https://github.com/herbstluftwm/herbstluftwm/issues/1173)

**To Reproduce**
1. Start Picom
2. Open Zathura/Alacritty
3. You can see that it has a transparent border

**Expected behavior**
![image](https://user-images.githubusercontent.com/60578218/131353198-aa902141-a895-4cb7-b6a3-20c0c44db03e.png)
You can see that it doesn't have a semi-transparent border.

**Current Behavior**
![image](https://user-images.githubusercontent.com/60578218/131353515-2b9b5062-6cd1-44c3-a0b7-a888fcda7136.png)
With picom opened as a daemon, it has some weird semi-transparent border around it.

**Comment by avahe-kellenberger** [comment]
Thanks for bringing this to my attention (and the related issue in other WMs).

If it's not much trouble, check out this PR:
https://github.com/avahe-kellenberger/nimdow/pull/178

Everything seems to be in order but an extra set of eyes is always welcomed.
