### ISSUE TITLE
Scroll on statusbar should go to prev or next tag

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#182]
Suggested by @dakyskye

**Comment by dakyskye** [comment]
I am on it, I just need to know how to find current tag for a monitor in [handleButtonPressed](https://github.com/avahe-kellenberger/nimdow/blob/a54de8c198eb106fa3d6b013885e7e5ba17e7f2d/src/nimdowpkg/windowmanager.nim#L1709) handler.
