### ISSUE TITLE
Load border and gap settings from config file

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#19]
Currently these settings are constants in `windowmanager.nim`.

- Add a parent config section named `[keybindings]` (so we can separate these from window settings)
- Add a parent config section named `[windows]`

Under `[windows]` we will need the following settings:
- borderWidth
- borderColorFocused
- borderColorUnfocused
- gapSize

Notes:
- See the [toml repo](https://github.com/toml-lang/toml#example) for examples
- We may want to allow different settings per layout (an override of the default). Open for discussion.

**Comment by avahe-kellenberger** [comment]
Closed via #38

**Comment by dakyskye** [comment]
Great :+1:
