### ISSUE TITLE
Is there a way to get my volume up/down, and my brightness up/down keys working

### ISSUE THREAD

**Issue by Infinitybeond1** [avahe-kellenberger/nimdow#193]
i was wondering if there were any keybindings i can use to do that

**Comment by avahe-kellenberger** [comment]
Currently all key bindings require a modifier (like super, alt, ctrl). I'll make an issue to allow non-modifier key bindings so you can create `[[startProcess]]` blocks for `XF86MonBrightnessUp` etc.

Currenly, I am using [sxhkd](https://github.com/baskerville/sxhkd) for these use cases. Reason being, you can use the same config for all window managers.

**Comment by Infinitybeond1** [comment]
ok thx
