### ISSUE TITLE
Powerline symbols in bar?

### ISSUE THREAD

**Issue by Infinitybeond1** [avahe-kellenberger/nimdow#195]
I was wondering how to get powerline symbols in the bar as shown in this screenshot
![132368685-570a2629-f948-4f24-9ab8-00804824a497](https://user-images.githubusercontent.com/88919270/162644091-d815275c-dad7-4661-9c2f-61356ac7868e.png)

**Comment by dakyskye** [comment]
Hi, have a look at issue #120 there is some code snippet for those powerline symbols on the status bar.

**Comment by Infinitybeond1** [comment]
Oh thx
