### ISSUE TITLE
xranr script in LightDM causing Bar issues

### ISSUE THREAD

**Issue by johnmain** [avahe-kellenberger/nimdow#197]
**issue**
With a 4 monitor configuration with monitor placement setup in the LightDM config file the Bar only shows on 2 of the monitors and is only fully working on one of them.

Also I am not seeing any tray Icons.

lightdm.conf file under [Seat:*]
`display-setup-script=xrandr --output DisplayPort-1 --auto --pos 0x0 --set "TearFree" on --output HDMI-A-0 --auto --pos 1920x0 --set "TearFree" on --output DisplayPort-2 --auto --pos 0x1080 --set "TearFree" on --output DisplayPort-0 --auto --pos 1920x1080 --set "TearFree" on
`

**To Reproduce**
Add a multimonitor xrandr config in LightDM Conf file

**Expected behavior**
Bar should show up on all Monitors

**Screenshots**
![Screenshot_2022-05-16_13-26-53](https://user-images.githubusercontent.com/2589334/168650121-7074f800-fc27-40f2-8f79-61580aae04e0.png)

**Comment by johnmain** [comment]
Same issue if I use xorg config
`Section "Monitor"
    Identifier "DisplayPort-1"
    Option "PreferredMode" "1920x1080"
    Option "Primary" "1"
EndSection
Section "Monitor"
    Identifier "HDMI-A-0"
    Option "PreferredMode" "1920x1080"
    Option "RightOf" "DisplayPort-1"
EndSection
Section "Monitor"
    Identifier "DisplayPort-2"
    Option "PreferredMode" "1920x1080"
    Option "Below" "DisplayPort-1"
EndSection
Section "Monitor"
    Identifier "DisplayPort-0"
    Option "PreferredMode" "1920x1080"
    Option "RightOf" "DisplayPort-2"
EndSection`

**Comment by avahe-kellenberger** [comment]
I believe it's a bug with the bar location - I pushed a fix to https://github.com/avahe-kellenberger/nimdow/tree/vertical-monitors-bug if you're able to build from source, and test out the change.

If you can't, I'll try setting up another monitor and testing it on my end

**Comment by avahe-kellenberger** [comment]
Fixed in https://github.com/avahe-kellenberger/nimdow/commit/8338649aa0e75b960d132e4e125557bd9716d5ec
