### ISSUE TITLE
Xfce4-screenshooter launches invisible

### ISSUE THREAD

**Issue by johnmain** [avahe-kellenberger/nimdow#198]
**Describe the bug**
Launching the Xfce4-screenshooter app doesn't show a window.  The Title is in the Bar.  If you switch the window to full screen or toggle floating the window will appear.

**To Reproduce**
Launch Xfce4-screenshooter app

**Expected behavior**
Window should appear visible

**Additional context**
I tried adding an App rule to force the app in floating mode since it really should be.  However, this didn't change things.

**Comment by avahe-kellenberger** [comment]
Looks like an issue with vertical monitors, will be investigating it tomorrow when I get a second monitor set up

**Comment by avahe-kellenberger** [comment]
I've just tried to recreate this bug with 2 monitors: The primary monitor on top, and a secondary monitor below. Seems to be working fine, no matter which monitor I launch it from
What's your monitor layout, and does it not work if launched from any monitor?

**Comment by avahe-kellenberger** [comment]
Fixed in 8f929c8d201f4a3ba3c3066928fcecc0b7086b07
