### ISSUE TITLE
Adding gaps and borders when there is only one window in the workspace

### ISSUE THREAD

**Issue by watchusayams** [avahe-kellenberger/nimdow#200]
As the title says, when there is 2 windows open there is gaps and a border around the focuses window. I would like if this was also available when there is only 1 window open on the workspace

**Comment by avahe-kellenberger** [comment]
Implemented in https://github.com/avahe-kellenberger/nimdow/commit/b7b88c480b907dea2941e41872d7fa8557ad01d1
