### ISSUE TITLE
Open apps floating with a specified width and height

### ISSUE THREAD

**Issue by 5RVLyre** [avahe-kellenberger/nimdow#201]
Hi I am new to Nimdow! (great wm and great job!) I can't find a way to make an apprule on how to open app floating with a specific height x width! (asked about it on Discord and they pointed me here!)

womp

**Comment by avahe-kellenberger** [comment]
I'll make that an option, good idea!

**Comment by avahe-kellenberger** [comment]
Implemented in e6740ed508df509d7952ece051ceace164140d24
