### ISSUE TITLE
Use config file for monocle layout

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#21]
Blocked by #19 

- Create a block in the config file for the monocle layout (gaps, window border size and color)
- Default to no gaps and no border (config file will override these settings)

**Comment by uninhm** [comment]
gaps? how? If there is just one window...

**Comment by avahe-kellenberger** [comment]
Currently there are no gaps when there's one window, but I could add a config option if you want to open an issue?

**Comment by dakyskye** [comment]
They are so called useless gaps which people use to make their TWM look fancy. Been a huge fan of it, but I've been using Nimdow for so long now that I'm pretty sure I'd not use "useless gaps" hahah. Though, it'd be awesome if Nimdow supported them.
