### ISSUE TITLE
Is there a command to restart the top bar only?

### ISSUE THREAD

**Issue by lf-araujo** [avahe-kellenberger/nimdow#210]
**Describe the bug**
Not a bug, the top bar gets weird in Nvidia with an external monitor.

- Is there a way to restart it? So it can detect the new monitor?

**To Reproduce**

Reboot the laptop using the nVidia driver and an external monitor

**Expected behavior**
Just a regular top bar

**Screenshots**
![image](https://user-images.githubusercontent.com/10139950/215349708-a6972efa-4962-4cc7-a54a-a2c769d4edf5.png)

**Comment by avahe-kellenberger** [comment]
Is the issue that there's no bar on the 2nd monitor?

Nimdow doesn't detect randr changes _after_ nimdow has been started, if that's what you're running into. You'd have to run your xrandr command when starting X, before launching Nimdow
