### ISSUE TITLE
Zoom darkens the whole screen while sharing screen

### ISSUE THREAD

**Issue by lf-araujo** [avahe-kellenberger/nimdow#229]
**Describe the bug**
Trying to share screen in Zoom will make a dark overlay appear, severely hindering readability of the screen. 

**To Reproduce**
1. Start Zoom. 
2. Share the screen

**Expected behavior**
Clear fonts and readable image.

**Screenshots**
I unfortunately can't capture the effect, will keep trying and later add if I manage to do so.

**Comment by DrunkenAlcoholic** [comment]
I am not familiar with Zoom, however I did install it to see if I could replicate the issue, from the local preview it looks fine from my end, however I would need to test this from the other end to ensure the "viewer" who is viewing your shared screen can see it clearly. it should be noted that there was slight black tint when my picom compositor was running, but after turning that off it was fine.
