### ISSUE TITLE
Focus always on window where cursor is when moving windows

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#30]
**To Reproduce**
1. Put your cursor in the top-left area of the screen
2. Open at least two windows
3. Move the master window next (super + shift, j)
4. Focus will be on the "new" master instead of the window that you moved

**Expected behavior**
Focus should always follow the window you selected to move initially

**Additional context**
This is cause by `EnterNotify` events, which we use to manually select windows. The cursor technically is entering a new window.

**Comment by dakyskye** [comment]
Also, focus a window when you click it!  Sometimes it happens that you left cursor where new window (which gets focused) is not placed, so you need to move your mouse.

**Comment by avahe-kellenberger** [comment]
I'm going to be replicating dwm's behavior for this issue, namely:

- When a window is mapped (becomes visible), the cursor will be warped (moved immediately) to the center of that window
- When changing window selection with a keybinding, the cursor will be warped in the same aforementioned manner

This isn't exactly how I wanted the behavior initially, but it works well and doesn't require extra libs or bad hacks I'd have to use to achieve the initial behavior I originally wanted.

If there are concerns please let me know.

**Comment by 0xACE** [comment]
I wouldn't recommend warping the cursor. But if you do, at least give an option that lets the cursor remain unaffected.

**Comment by unihernandez22** [comment]
> More updates pushed, fixed a major but with some weird applications.

Awesome, you fixed a bug that I hadn't yet reported.
