### ISSUE TITLE
Systray support

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#46]
A few helpful links:
[systray protocol specification](https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.2.html)
[dwm systray patch](https://dwm.suckless.org/patches/systray/dwm-systray-20200610-f09418b.diff)

**Comment by avahe-kellenberger** [comment]
Systray support being added in the [systray](https://github.com/avahe-kellenberger/nimdow/tree/systray) branch

Current progress:
![image](https://user-images.githubusercontent.com/34498340/92464672-76962e00-f19b-11ea-96b9-d3632b91d770.png)

**Comment by dakyskye** [comment]
Well done :+1:
