### ISSUE TITLE
Built in keybindings do not work whilst numlock is on

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#53]
**Describe the bug**
No defined keybinding (in the config file) work when numlock is on

**To Reproduce**
1) log into nimdow session
2) turn numlock on (`numlockx on`)
3) try using any of the keybindings
4) see the result

**Expected behavior**
Keybindings should work whilst numlock is on

**Screenshots**

**Additional context**

**Comment by avahe-kellenberger** [comment]
Working on this tonight, shouldn't take long.
