### ISSUE TITLE
(probably) nimdow processes become zombies

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#54]
**Describe the bug**
When a process is finished (the ones I put in autostart, in config), it becomes a zombie process

**To Reproduce**
1) add application to autostart
2) kill it
3) check it's statistic
4) it should be zomebie (like in my case)

**Expected behavior**
A process should have not become a zombie

**Screenshots**
![image](https://user-images.githubusercontent.com/32128756/85023985-7e3ecb80-b186-11ea-94f7-05023e17ad1a.png)

**Additional context**

**Comment by avahe-kellenberger** [comment]
If you want to look into this, it has to do with [this line](https://github.com/avahe-kellenberger/nimdow/blob/master/src/nimdowpkg/config/configloader.nim#L88).
See [the docs](https://nim-lang.org/docs/osproc.html#startProcess%2Cstring%2Cstring%2CopenArray%5Bstring%5D%2CStringTableRef%2Cset%5BProcessOption%5D) (we may have to use a different proc, options, close the process or something). Working on other things atm.

**Comment by avahe-kellenberger** [comment]
I've found a fix for this, but it's not great. Doing some more research before implementing it.
