### ISSUE TITLE
Reloadable config file

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#66]
Need to add a way to reload the configuration file, so the user doesn't have to log out and back in to see changes take effect.

**Comment by dakyskye** [comment]
My idea is to use signals.  Run `while true:` loop under https://github.com/avahe-kellenberger/nimdow/blob/master/src/nimdow.nim#L8, and start threads for `eventManager.startEventListenerLoop(nimdow.display)` and signal receiver, which will terminate nimdow for signals, that are neither SIGUSR1 nor SIGUSR2.  Catch these user defined signals, and `continue` the infinite loop.

**Comment by avahe-kellenberger** [comment]
This isn't to reload Nimdow, just the config file - so we can change key bindings, colors, gaps, etc. on the fly without the program actually restarting. Restarting the wm will be another feature implemented later

**Comment by dakyskye** [comment]
Oh I see.

**Comment by avahe-kellenberger** [comment]
Closed via #70
