### ISSUE TITLE
Allow tags to be defined for application autostarting

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#68]
Under the autostart configuration section, each application should have an array of tags that define where the applications will launch. We should also consider the monitor number.

This is similar to #52 and should take precedence.

**Comment by dakyskye** [comment]
I had exactly that in mind when I opened #52.  You don’t need to add rule for autostart applications, you just add general rules, and autostart applications follow them.

**Comment by dakyskye** [comment]
But I think this issue is good.  Should be optional to define tags for autostart apps.  Can be found useful.

**Comment by deoradh** [comment]
So question:  how does that work with, say, having different instances of a browser.

EG: Say I have a tag associated with work, and a browser instances with open tabs to various intranet sites.  Say I then also have a tag associated with play, which a browser instance with open tabs to YouTube and Netflix.

Part of that begs the question of being able to either launch with multiple URLs, or being table to target specific instances with a launch request.  But, browsers being what they are, which today is "tabbed", it quickly impacts things.  Other cases would include various editors or terminals: consider a tag per project, with terminals and editors each but open to project-specific locations.

**Comment by avahe-kellenberger** [comment]
This is specifically for starting applications automatically when Nimdow first launches - Each application would start in the order that they are defined.

So, in order to launch two instances of your browser with different commands, you'd just have two different definitions.

Something like...
```
[[autostart]]
command = "firefox"
tags = [ 1, 3, 5 ]
monitor = 1

[[autostart]]
command = "firefox --new-window 'https://blog.avahe.tk'"
tags = [ 2, 4, 6 ]
monitor = 2
```

**Comment by dakyskye** [comment]
Any updates on this?

**Comment by avahe-kellenberger** [comment]
Will probably do this within the next week

**Comment by dakyskye** [comment]
It should be easy to also do #52 after this or vice a versa though.

**Comment by avahe-kellenberger** [comment]
I think I'll actually combine this with #52 now that I've thought about it more.

Still need to sort out exactly how I want to handle this in the config and in the code. Will probably be a bit longer, I've been distracted with another project @dakyskye, but this is coming.
