### ISSUE TITLE
Allow display names and icons for tags

### ISSUE THREAD

**Issue by deoradh** [avahe-kellenberger/nimdow#71]
Consider allowing display names to be associated with tags, such that when rendered in the bar we might have:

```
[Web] {code} >term Work Project-1 Project-2
```

Related, or alternatively, allowing icons (Unicode glyph(s)? png? svg? any media?) to be specified.  In that case I might suggest a display mode flag: Id | Name | Icon | IconName | IdIconName.

**Comment by avahe-kellenberger** [comment]
My plan has been to allow the user to define alternate text per each tag ID (we'd have a map in the config from ID (int) to a string). This would allow for unicode chars, in the same way you would have in the status bar text. Wouldn't be too hard to implement. What are your thoughts?

**Comment by deoradh** [comment]
Alternative text goes far and would be comparatively performant. We used that for the Bing/MSN OOB apps on Win8 for that reason, and its only drawback is that it's limited to the specific characters in whichever font is used, so we'd need to be able to specify font.  

We'd want to also specify font color I think, but we shouldn't get into the question of using multiple characters to compose a multicolor glyph.  It does, however, raise the question of color for selection state, and perhaps focus and mouse hover states.  Those are pretty simple questions to address.

I think go for it.

The font limitations are why I suggested the possibility of SVG.  That said, given your plan SVG and the like can be easily considered at a later time.  Moreso if we've referrals to a simple font editor.

This is gonna compel me to install Linux, isn't it?  It's been a couple decades.  Blame Rust and (at some point) Nim.

**Comment by avahe-kellenberger** [comment]
The config file already allows you to define an array of fonts to use, and some limited colors.

I pretty much never use my mouse, so I didn't think to add mouse interaction with the bar - but if the people want it, I'll add it.

My love for Linux runs deep, you should definitely install.

**Comment by deoradh** [comment]
Consider accessibility -- support for alternative input devices is generally a good idea.  Also, I'm interested in trying out a tablet as a remote client for some things, so there's another non-keyboard area.  Obviously not for programming at that point.

I enjoyed Linux circa 1993-1998, but I had other needs computing wise.  Things have finally matured where I can devote a machine to it to offload some analytical projects from my Surface.

**Comment by avahe-kellenberger** [comment]
Finally got around to implementing this, closed via #121 

See [the wiki](https://github.com/avahe-kellenberger/nimdow/wiki/User-Configuration-File#changing-text-of-tags-) for configuration details.
