### ISSUE TITLE
Command line client

### ISSUE THREAD

**Issue by dakyskye** [avahe-kellenberger/nimdow#72]
Just like i3 wm has i3-msg, bspwm has bspc, qtile has qtile-cmd, herbstluftwm has herbsclient etc. Nimdow should also have a cmdline client, that will allow users to do everything Nimdow can with it.

**Comment by avahe-kellenberger** [comment]
Planned for the future, just isn't a priority atm

**Comment by unihernandez22** [comment]
Yes, and with that you can add a nimdowrc file where you use the client commands (like bspwm).

**Comment by unihernandez22** [comment]
So you don't need another config method

**Comment by dakyskye** [comment]
Yeah, but that'd work only if you execute a shell script (nimdowrc or whatever) with xinit etc. I'd personally use the cmdline client with [dxhd](https://github.com/dakyskye/dxhd) for keybindings (yes I could just use the config file).

**Comment by avahe-kellenberger** [comment]
disruptek from irc suggested looking into i3ipc for this feature. I might actually do this sooner, rather than later.

**Comment by avahe-kellenberger** [comment]
I am contemplating a way to implement #68 with the cli client.

Perhaps `~/.config/nimdow/startup.sh` will be executed on startup, and the user can invoke cli commands from the script which tells Nimdow where certain window names/classes should spawn.

Let me know your thoughts.

**Comment by unihernandez22** [comment]
Yeah that's what I said [here](https://github.com/avahe-kellenberger/nimdow/issues/72#issuecomment-670976477)

**Comment by avahe-kellenberger** [comment]
See #95 for more use cases of the cli client.

**Comment by avahe-kellenberger** [comment]
In progress on the [cli branch](https://github.com/avahe-kellenberger/nimdow/tree/cli).

Should be ready for a small release by the end of the week.
