### ISSUE TITLE
controls.destroySelectedWindow destroys all instances of the program

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#73]
**Describe the bug**
controls.destroySelectedWindow destroys all instances of the program

**To Reproduce**
1. Open 3 terminals
2. Try to close one with `Super + Shift + Q`

**Expected behavior**
Close only the selected window

**Comment by avahe-kellenberger** [comment]
I'll fix this today and submit a new release

**Comment by unihernandez22** [comment]
I think this option is useful, so you can rename to destroySelectedProgramInstances and add another keybind (Super + Shift + C) for destroySelectedWindow.

You can choose other name too.

**Comment by avahe-kellenberger** [comment]
Fixed - if you notice any issues just comment here again.
