### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#74]
**Describe the bug**
The tag bugs (I don't know what happens)

**To Reproduce**
Steps to reproduce:
1. Go to `tag 1`
2. Open Telegram
3. Go to `tag 2`
4. Open any window (A terminal for example)
5. Wait a Telegram notification
6. Click it
7. `tag 2` bugs

**Comment by avahe-kellenberger** [comment]
Can you provide a screenshot or gif? I'm not seeing any issues (using dunst for notifications)

**Comment by unihernandez22** [comment]
Now I don't have the bug, I don't know...
