### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#76]
**Describe the bug**
I feel I'm in Windows XP xD

**To Reproduce**
1. Open a Window
2. Resize it to 0x0
3. Increase it size

**Screenshots**
![image](https://user-images.githubusercontent.com/62044675/89718874-2314a280-d999-11ea-8092-161b22596def.png)

![image](https://user-images.githubusercontent.com/62044675/89718954-d9788780-d999-11ea-90d8-6a1b3990ed42.png)

![image](https://user-images.githubusercontent.com/62044675/89718999-32482000-d99a-11ea-9cc2-66d8569ea43a.png)

**Comment by avahe-kellenberger** [comment]
Which program is this? It's not happening for any program I've tried

**Comment by unihernandez22** [comment]
> Which program is this? It's not happening for any program I've tried

Tilix

**Comment by unihernandez22** [comment]
But it occurs with all programs I've tried

**Comment by avahe-kellenberger** [comment]
It seems to only be happening to me with Tilix, but only when I don't have a compositor running.. It's an interesting bug, I'll look into this soon.

**Comment by avahe-kellenberger** [comment]
Fixed via https://github.com/avahe-kellenberger/nimdow/commit/691001a410beef0e0f8b3960847a57c743fe9564
If this still persists for you, please let me know
