### ISSUE TITLE
Autostart doesn't work

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#77]

**Comment by avahe-kellenberger** [comment]
Can you show your config file and X logs? It's working for me

**Comment by unihernandez22** [comment]
[Here](https://gist.github.com/unihernandez22/a8a20c3c7db806163b3222d85d289e60)

**Comment by avahe-kellenberger** [comment]
Thanks, I've spotted the issue. I'll fix it soon.

**Comment by avahe-kellenberger** [comment]
Fixed - v0.6.4 released.

**Comment by unihernandez22** [comment]
> Thanks, I've spotted the issue. I'll fix it soon.

What was?
