### ISSUE TITLE
Telegram Bugs

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#79]
**Describe the bug**
This bug isn't happening in awesomeWM, so the problem is the WM.

**To Reproduce**
1. Open Telegram
2. Click on an image
3. Close the image
4. Click on an image (Can be the same)
5. Telegram freezes

**Comment by unihernandez22** [comment]
Ok, I know what's happening. Telegram's image viewer is opening invisible (When I change to another tag and go back, it comes visible)

**Comment by avahe-kellenberger** [comment]
I think this is caused by the same issue as the resizing bug - I'll see if I can fix it when I'm back from vacation

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/89799401-cd103e00-db03-11ea-9a57-0eaad798da1f.png)

You can see (Really not) the invisible media viewer

**Comment by unihernandez22** [comment]
@avahe-kellenberger And, when I close with the X in the corner of Media Viewer, I have this problem. But if I close it with `Super + Shitf + Q` (controls.destroySelectedWindow) I have no problem

**Comment by unihernandez22** [comment]
I think you have to intercept the xatom `WM_DELETE_WINDOW`

**Comment by avahe-kellenberger** [comment]
It looks like I have a fix (installed Telegram to test). I'm testing it via settings -> Use system window frame, since that had a similar issue and I don't have to log in. 

If you could test it out for your particular case, that would be great. [Here's the branch with the fix](https://github.com/avahe-kellenberger/nimdow/tree/reused-window-fix). I'll be testing it out myself to make sure nothing breaks from the change.

**Comment by unihernandez22** [comment]
Ok, it's solved. Now there is a lot of other issues

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/90064538-4bfea580-dcc1-11ea-9523-7da2e129c87e.png)

The media viewer opens behind telegram

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/90064832-b9123b00-dcc1-11ea-8288-22c00d9e734c.png)

Sometimes window is moved down

**Comment by unihernandez22** [comment]
And when move to another tag and go back, I allways get media viewer behind telegram

**Comment by avahe-kellenberger** [comment]
This is probably due to the way focus works (which will be changed) - whichever window your cursor enters will be focused/raised. If this doesn't sound like what is causing this issue, please let me know.

**Comment by unihernandez22** [comment]
@avahe-kellenberger you shouldn't close until this is soved, for the moment this is a bug.

**Comment by avahe-kellenberger** [comment]
The focus change is open in another issue, unless this has to do with another problem?

**Comment by unihernandez22** [comment]
![image](https://user-images.githubusercontent.com/62044675/90283367-7f1e7180-de46-11ea-86e5-ca7d44fd882b.png)

The Image Viewer should open full screen, and sometimes the window is moved down: https://github.com/avahe-kellenberger/nimdow/issues/79#issuecomment-673096065

**Comment by unihernandez22** [comment]
When will you merge this to the master branch?

**Comment by avahe-kellenberger** [comment]
I'm actively working on it, just a few kinks to work out. Should be done by this weekend at the latest
