### ISSUE TITLE
Off-center bar

### ISSUE THREAD

**Issue by unihernandez22** [avahe-kellenberger/nimdow#82]
**Describe the bug**
The bar contents are moved to the top

**Screenshots**
![image](https://user-images.githubusercontent.com/62044675/90155573-deef1c80-dd61-11ea-9001-9f69abaf2977.png)

**Comment by avahe-kellenberger** [comment]
Did this happen once or is it always like this? It's centered on all devices I've seen

**Comment by unihernandez22** [comment]
> Did this happen once or is it always like this? It's centered on all devices I've seen

It's always like this

**Comment by avahe-kellenberger** [comment]
Can you show your config file and which font you're using? The bar has math to center the text vertically, so maybe the font has something weird going on... In the meantime, see if changing the font makes a difference

**Comment by unihernandez22** [comment]
[This](https://gist.github.com/unihernandez22/a8a20c3c7db806163b3222d85d289e60) is my config file

**Comment by avahe-kellenberger** [comment]
Try other fonts than `monospace` maybe? It seems like there may be padding on whatever font you are using. Let me know how experimenting goes.

**Comment by unihernandez22** [comment]
You are right, the problem is monospace. This is with FiraCode:
![image](https://user-images.githubusercontent.com/62044675/90324037-1a474200-df40-11ea-92c2-a4f28535463b.png)

And this with JetbrainsMono:
![image](https://user-images.githubusercontent.com/62044675/90324050-38ad3d80-df40-11ea-8891-309b3711107a.png)

**Comment by unihernandez22** [comment]
The most centered is JetbrainsMono

**Comment by avahe-kellenberger** [comment]
Awesome!
