### ISSUE TITLE
Execute multiple controls from a key binding

### ISSUE THREAD

**Issue by avahe-kellenberger** [avahe-kellenberger/nimdow#95]
One of the users requested a control which is to change monitors and then change tags.

This gave me the idea to execute the two existing controls in order with one keybinding, which would mean 0 code change with a lot of flexibility.

The current configloader does not allow for this paradigm, but it would be very helpful to add.

**Comment by avahe-kellenberger** [comment]
In order to do this, I'd probably want a separate file with a schema similar to sxhkd/dxhd.

Instead of re-implementing that, I'd rather write the cli client and allow the user to invoke multiple commands through the hotkey daemon.

@dakyskye Any thoughts on these two options? I could implement both, but it seems like a waste to me.

**Comment by dakyskye** [comment]
Yes, we should expose everything Nimdow can do as a nimdow's commands, so users can do much with CLI. sxhkd/dxhd can do this job well, that's their main goal.

**Comment by avahe-kellenberger** [comment]
I'm going to close this and mention it in #72
